version: '3.9'

services:
  sqlserverdocker:
    container_name: sql-server-docker
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "8006:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Mys3cureP@ssw0rd
    networks:
      - mynetworkapi

  apiuser:
    build:
      context: .
      dockerfile: ApiUser/Dockerfile
    image: apiuser
    networks:
      - mynetworkapi
    depends_on:
      - sqlserverdocker
    ports:
      - "5001:8001"
    environment:
      - DB_CONNECTION_STRING=Server=sqlserverdocker;Database=API_USERS;User Id=sa;Password=Mys3cureP@ssw0rd;Encrypt=False;TrustServerCertificate=True

networks:
  mynetworkapi:
